package pl.recipesforsoftware.signalbrief.data.local.db

import app.cash.turbine.test
import kotlinx.coroutines.test.runTest
import pl.recipesforsoftware.signalbrief.data.local.dao.CollectionDao
import pl.recipesforsoftware.signalbrief.data.local.entity.CollectionEntity
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class CollectionDaoTest {
    private lateinit var database: SignalBriefDatabase
    private lateinit var dao: CollectionDao

    @BeforeTest
    fun setup() {
        database = createTestDatabase()
        dao = database.collectionDao()
    }

    @AfterTest
    fun tearDown() {
        database.close()
    }

    @Test
    fun insertAndObserve_returnsInsertedCollection() =
        runTest {
            val id = dao.insert(entity(name = "Reading", createdAt = 1000L))

            dao.observeAll().test {
                val items = awaitItem()
                assertEquals(1, items.size)
                assertEquals(id, items.single().id)
                assertEquals("Reading", items.single().name)
                assertEquals(1000L, items.single().createdAt)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun insert_returnsAutoGeneratedId() =
        runTest {
            val first = dao.insert(entity(name = "First", createdAt = 1000L))
            val second = dao.insert(entity(name = "Second", createdAt = 2000L))

            assertTrue(first != second)
            assertEquals(1L, first)
            assertEquals(2L, second)
        }

    @Test
    fun multipleInserts_orderedByCreatedAtDesc() =
        runTest {
            dao.insert(entity(name = "First", createdAt = 1000L))
            dao.insert(entity(name = "Second", createdAt = 3000L))
            dao.insert(entity(name = "Third", createdAt = 2000L))

            dao.observeAll().test {
                val items = awaitItem()
                assertEquals(3, items.size)
                assertEquals(
                    listOf("Second", "Third", "First"),
                    items.map { it.name },
                )
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun sameTimestamp_orderedByIdDesc() =
        runTest {
            dao.insert(entity(name = "First", createdAt = 1000L))
            dao.insert(entity(name = "Second", createdAt = 1000L))
            dao.insert(entity(name = "Third", createdAt = 1000L))

            dao.observeAll().test {
                val items = awaitItem()
                assertEquals(3, items.size)
                assertEquals(
                    listOf(3L, 2L, 1L),
                    items.map { it.id },
                )
                assertEquals(
                    listOf("Third", "Second", "First"),
                    items.map { it.name },
                )
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun updateName_returnsAffectedRows() =
        runTest {
            val id = dao.insert(entity(name = "Reading", createdAt = 1000L))

            val affected = dao.updateName(id, "To Read")

            assertEquals(1, affected)
            dao.observeAll().test {
                assertEquals("To Read", awaitItem().single().name)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun updateName_nonexistentId_returnsZero() =
        runTest {
            val affected = dao.updateName(999L, "New Name")

            assertEquals(0, affected)
        }

    @Test
    fun updateName_doesNotChangeCreatedAt() =
        runTest {
            val id = dao.insert(entity(name = "Reading", createdAt = 1000L))

            dao.updateName(id, "To Read")

            dao.observeAll().test {
                assertEquals(1000L, awaitItem().single().createdAt)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun deleteById_returnsAffectedRows() =
        runTest {
            val id = dao.insert(entity(name = "Reading", createdAt = 1000L))

            val affected = dao.deleteById(id)

            assertEquals(1, affected)
            dao.observeAll().test {
                assertTrue(awaitItem().isEmpty())
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun deleteById_nonexistentId_returnsZero() =
        runTest {
            dao.insert(entity(name = "Reading", createdAt = 1000L))

            val affected = dao.deleteById(999L)

            assertEquals(0, affected)
            dao.observeAll().test {
                assertEquals(1, awaitItem().size)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun clearAll_removesAllCollections() =
        runTest {
            dao.insert(entity(name = "First", createdAt = 1000L))
            dao.insert(entity(name = "Second", createdAt = 2000L))

            dao.clearAll()

            dao.observeAll().test {
                assertTrue(awaitItem().isEmpty())
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun observeAll_emitsCurrentAndUpdates() =
        runTest {
            dao.observeAll().test {
                assertEquals(emptyList(), awaitItem())

                dao.insert(entity(name = "First", createdAt = 1000L))
                assertEquals(1, awaitItem().size)

                dao.insert(entity(name = "Second", createdAt = 2000L))
                assertEquals(2, awaitItem().size)

                cancelAndIgnoreRemainingEvents()
            }
        }

    private companion object {
        fun entity(
            name: String,
            createdAt: Long,
        ): CollectionEntity =
            CollectionEntity(
                id = 0,
                name = name,
                createdAt = createdAt,
            )
    }
}
