package pl.recipesforsoftware.signalbrief.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room persistence model for a user's saved-article collection.
 *
 * [id] is auto-generated by Room and unique per collection. [name] stores the
 * normalized, non-blank collection name. [createdAt] is a Unix-epoch
 * millisecond timestamp used for newest-first ordering; it is set at creation
 * time and never updated on rename.
 */
@Entity(
    tableName = "collections",
    indices = [
        Index(value = ["created_at"]),
    ],
)
internal data class CollectionEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,
    @ColumnInfo(name = "name") val name: String,
    @ColumnInfo(name = "created_at") val createdAt: Long,
)
