package pl.recipesforsoftware.signalbrief.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room persistence model for a monitored topic.
 *
 * [id] is auto-generated by Room and unique per topic. [query] stores the
 * normalized (trimmed) user-facing query with its original casing.
 * [normalizedQuery] stores a deterministic case-insensitive key used for
 * duplicate detection and ordering without depending on SQLite locale/collation
 * behavior; it is unique so two topics with the same normalized query cannot
 * coexist.
 */
@Entity(
    tableName = "monitored_topics",
    indices = [
        Index(value = ["normalized_query"], unique = true),
    ],
)
internal data class MonitoredTopicEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,
    @ColumnInfo(name = "query") val query: String,
    @ColumnInfo(name = "normalized_query") val normalizedQuery: String,
)
