package pl.recipesforsoftware.signalbrief.data.local.db

import app.cash.turbine.test
import kotlinx.coroutines.test.runTest
import pl.recipesforsoftware.signalbrief.data.local.dao.MonitoredTopicDao
import pl.recipesforsoftware.signalbrief.data.local.entity.MonitoredTopicEntity
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class MonitoredTopicDaoTest {
    private lateinit var database: SignalBriefDatabase
    private lateinit var dao: MonitoredTopicDao

    @BeforeTest
    fun setup() {
        database = createTestDatabase()
        dao = database.monitoredTopicDao()
    }

    @AfterTest
    fun tearDown() {
        database.close()
    }

    @Test
    fun insertAndObserve_returnsInsertedTopic() =
        runTest {
            val id = dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))

            dao.observeAll().test {
                val items = awaitItem()
                assertEquals(1, items.size)
                assertEquals(id, items.single().id)
                assertEquals("Kotlin", items.single().query)
                assertEquals("kotlin", items.single().normalizedQuery)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun insert_returnsAutoGeneratedId() =
        runTest {
            val first = dao.insert(entity(query = "First", normalizedQuery = "first"))
            val second = dao.insert(entity(query = "Second", normalizedQuery = "second"))

            assertTrue(first != second)
            assertEquals(1L, first)
            assertEquals(2L, second)
        }

    @Test
    fun multipleInserts_orderedByNormalizedQueryAscending() =
        runTest {
            dao.insert(entity(query = "Zebra", normalizedQuery = "zebra"))
            dao.insert(entity(query = "alpha", normalizedQuery = "alpha"))
            dao.insert(entity(query = "Apple", normalizedQuery = "apple"))
            dao.insert(entity(query = "Market", normalizedQuery = "market"))

            dao.observeAll().test {
                val items = awaitItem()
                assertEquals(4, items.size)
                assertEquals(
                    listOf("alpha", "apple", "market", "zebra"),
                    items.map { it.normalizedQuery },
                )
                assertEquals(
                    listOf("alpha", "Apple", "Market", "Zebra"),
                    items.map { it.query },
                )
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun existsByNormalizedQuery_returnsTrueWhenPresent() =
        runTest {
            dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))

            assertTrue(dao.existsByNormalizedQuery("kotlin"))
            assertFalse(dao.existsByNormalizedQuery("swift"))
        }

    @Test
    fun existsByNormalizedQueryExcluding_ignoresOwnId() =
        runTest {
            val id = dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))
            dao.insert(entity(query = "Swift", normalizedQuery = "swift"))

            assertTrue(dao.existsByNormalizedQueryExcluding("kotlin", 2))
            assertFalse(dao.existsByNormalizedQueryExcluding("kotlin", id))
        }

    @Test
    fun insert_normalizedQueryUniqueIndexRejectsDuplicate() =
        runTest {
            dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))

            assertFailsWith<Exception> {
                dao.insert(entity(query = "kotlin", normalizedQuery = "kotlin"))
            }
        }

    @Test
    fun updateQuery_updatesQueryAndNormalizedQuery() =
        runTest {
            val id = dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))

            val affected = dao.updateQuery(id, "Swift", "swift")

            assertEquals(1, affected)
            dao.observeAll().test {
                val item = awaitItem().single()
                assertEquals("Swift", item.query)
                assertEquals("swift", item.normalizedQuery)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun updateQuery_nonexistentId_returnsZero() =
        runTest {
            val affected = dao.updateQuery(999L, "Swift", "swift")

            assertEquals(0, affected)
        }

    @Test
    fun deleteById_returnsAffectedRows() =
        runTest {
            val id = dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))

            val affected = dao.deleteById(id)

            assertEquals(1, affected)
            dao.observeAll().test {
                assertTrue(awaitItem().isEmpty())
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun deleteById_nonexistentId_returnsZero() =
        runTest {
            dao.insert(entity(query = "Kotlin", normalizedQuery = "kotlin"))

            val affected = dao.deleteById(999L)

            assertEquals(0, affected)
            dao.observeAll().test {
                assertEquals(1, awaitItem().size)
                cancelAndIgnoreRemainingEvents()
            }
        }

    @Test
    fun observeAll_emitsCurrentAndUpdates() =
        runTest {
            dao.observeAll().test {
                assertEquals(emptyList(), awaitItem())

                dao.insert(entity(query = "First", normalizedQuery = "first"))
                assertEquals(1, awaitItem().size)

                dao.insert(entity(query = "Second", normalizedQuery = "second"))
                assertEquals(2, awaitItem().size)

                cancelAndIgnoreRemainingEvents()
            }
        }

    private companion object {
        fun entity(
            query: String,
            normalizedQuery: String,
        ): MonitoredTopicEntity =
            MonitoredTopicEntity(
                id = 0,
                query = query,
                normalizedQuery = normalizedQuery,
            )
    }
}
